"""Agregar columnas clasificacion y fallo a Documento

Revision ID: 40edb294444c
Revises: 4febcb85b594
Create Date: 2026-09-18 16:31:12.092169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40edb294444c'
down_revision: Union[str, None] = '4febcb85b594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('terminos_detectados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('documentos', sa.Column('version_diccionario', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('motivo_fallo', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('cantidad_caracteres', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'cantidad_caracteres')
    op.drop_column('documentos', 'motivo_fallo')
    op.drop_column('documentos', 'version_diccionario')
    op.drop_column('documentos', 'terminos_detectados')
    # ### end Alembic commands ###
