"""Add columnas to riesgos

Revision ID: 850c907a5491
Revises: 40edb294444c
Create Date: 2026-09-18 17:00:30.893728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850c907a5491'
down_revision: Union[str, None] = '40edb294444c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riesgos_contractuales', sa.Column('codigo_regla', sa.String(), nullable=False))
    op.add_column('riesgos_contractuales', sa.Column('articulos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('riesgos_contractuales', sa.Column('evidencia', sa.String(), nullable=True))
    op.add_column('riesgos_contractuales', sa.Column('inicio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('riesgos_contractuales', 'inicio')
    op.drop_column('riesgos_contractuales', 'evidencia')
    op.drop_column('riesgos_contractuales', 'articulos')
    op.drop_column('riesgos_contractuales', 'codigo_regla')
    # ### end Alembic commands ###
