"""estructura de normas

Revision ID: 48e30a8c7cc4
Revises: 36da95aeae37
Create Date: 2026-09-17 21:20:46.224536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e30a8c7cc4'
down_revision: Union[str, None] = '36da95aeae37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    estado_vigencia_enum = postgresql.ENUM('vigente', 'derogado', 'modificado', 'sin_verificar', name='estadovigencia')
    estado_vigencia_enum.create(op.get_bind())
    op.add_column('normas', sa.Column('numero_articulo', sa.Integer(), nullable=False))
    op.add_column('normas', sa.Column('epigrafe', sa.String(), nullable=True))
    op.add_column('normas', sa.Column('libro', sa.String(), nullable=True))
    op.add_column('normas', sa.Column('parte', sa.String(), nullable=True))
    op.add_column('normas', sa.Column('capitulo', sa.String(), nullable=True))
    op.add_column('normas', sa.Column('seccion', sa.String(), nullable=True))
    op.add_column('normas', sa.Column('fuente_nombre', sa.String(), nullable=False))
    op.add_column('normas', sa.Column('fuente_url', sa.String(), nullable=False))
    op.add_column('normas', sa.Column('descargada_en', sa.DateTime(timezone=True), nullable=False))
    op.add_column('normas', sa.Column('estado_vigencia', estado_vigencia_enum, nullable=False))
    op.add_column('normas', sa.Column('nota_vigencia', sa.String(), nullable=True))
    op.alter_column('normas', 'area_juridica',
               existing_type=postgresql.ENUM('contratos', 'obligaciones', 'derechos_reales', 'sucesiones', 'responsabilidad_civil', name='areajuridica'),
               nullable=True)
    op.drop_index(op.f('ix_normas_articulo'), table_name='normas')
    op.create_index(op.f('ix_normas_numero_articulo'), 'normas', ['numero_articulo'], unique=False)
    op.create_unique_constraint('uq_normas_codigo_articulo_version', 'normas', ['codigo', 'numero_articulo', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_normas_codigo_articulo_version', 'normas', type_='unique')
    op.drop_index(op.f('ix_normas_numero_articulo'), table_name='normas')
    op.create_index(op.f('ix_normas_articulo'), 'normas', ['articulo'], unique=False)
    op.alter_column('normas', 'area_juridica',
               existing_type=postgresql.ENUM('contratos', 'obligaciones', 'derechos_reales', 'sucesiones', 'responsabilidad_civil', name='areajuridica'),
               nullable=False)
    op.drop_column('normas', 'nota_vigencia')
    op.drop_column('normas', 'estado_vigencia')
    op.drop_column('normas', 'descargada_en')
    op.drop_column('normas', 'fuente_url')
    op.drop_column('normas', 'fuente_nombre')
    op.drop_column('normas', 'seccion')
    op.drop_column('normas', 'capitulo')
    op.drop_column('normas', 'parte')
    op.drop_column('normas', 'libro')
    op.drop_column('normas', 'epigrafe')
    op.drop_column('normas', 'numero_articulo')
    
    estado_vigencia_enum = postgresql.ENUM('vigente', 'derogado', 'modificado', 'sin_verificar', name='estadovigencia')
    estado_vigencia_enum.drop(op.get_bind())
    # ### end Alembic commands ###
