"""Add hallazgos y reglas_evaluadas

Revision ID: 19fe03e0e270
Revises: 850c907a5491
Create Date: 2026-09-18 17:09:30.920255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fe03e0e270'
down_revision: Union[str, None] = '850c907a5491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis_documentos', sa.Column('hallazgos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('analisis_documentos', sa.Column('reglas_evaluadas', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis_documentos', 'reglas_evaluadas')
    op.drop_column('analisis_documentos', 'hallazgos')
    # ### end Alembic commands ###
