"""Add terminos_detectados and version_diccionario to consultas

Revision ID: 4febcb85b594
Revises: abcdef123456
Create Date: 2026-09-18 07:36:43.471223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4febcb85b594'
down_revision: Union[str, None] = 'abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('terminos_detectados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('consultas', sa.Column('version_diccionario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'version_diccionario')
    op.drop_column('consultas', 'terminos_detectados')
    # ### end Alembic commands ###
