"""modelos_dominios

Revision ID: 36da95aeae37
Revises: 568b308006d1
Create Date: 2026-09-17 13:59:55.462214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36da95aeae37'
down_revision: Union[str, None] = '568b308006d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('articulo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('area_juridica', sa.Enum('contratos', 'obligaciones', 'derechos_reales', 'sucesiones', 'responsabilidad_civil', name='areajuridica'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normas_articulo'), 'normas', ['articulo'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('area_juridica', sa.Enum('contratos', 'obligaciones', 'derechos_reales', 'sucesiones', 'responsabilidad_civil', name='areajuridica'), nullable=True),
    sa.Column('respuesta', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'completado', 'fallido', name='estadoproceso'), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_usuario_id'), 'consultas', ['usuario_id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('compraventa', 'arrendamiento', 'prestamo', 'acuerdo_civil', 'otro', name='tipodocumento'), nullable=True),
    sa.Column('texto_extraido', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'procesando', 'completado', 'fallido', name='estadoproceso'), nullable=False),
    sa.Column('subido_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_usuario_id'), 'documentos', ['usuario_id'], unique=False)
    op.create_table('documentos_generados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('compraventa', 'arrendamiento', 'prestamo', 'acuerdo_civil', 'otro', name='tipodocumento'), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('documento_padre_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_padre_id'], ['documentos_generados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_generados_usuario_id'), 'documentos_generados', ['usuario_id'], unique=False)
    op.create_table('analisis_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('resumen', sa.String(), nullable=True),
    sa.Column('partes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('obligaciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fechas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('montos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_documentos_documento_id'), 'analisis_documentos', ['documento_id'], unique=False)
    op.create_table('comparaciones_documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('documento_a_id', sa.Uuid(), nullable=False),
    sa.Column('documento_b_id', sa.Uuid(), nullable=False),
    sa.Column('diferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_a_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['documento_b_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparaciones_documentos_usuario_id'), 'comparaciones_documentos', ['usuario_id'], unique=False)
    op.create_table('fuentes_legales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consulta_id', sa.Uuid(), nullable=False),
    sa.Column('norma_id', sa.Uuid(), nullable=True),
    sa.Column('articulo', sa.String(), nullable=False),
    sa.Column('texto_citado', sa.String(), nullable=False),
    sa.Column('relevancia', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['norma_id'], ['normas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuentes_legales_consulta_id'), 'fuentes_legales', ['consulta_id'], unique=False)
    op.create_table('riesgos_contractuales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analisis_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('severidad', sa.Enum('alta', 'media', 'baja', name='severidadriesgo'), nullable=False),
    sa.Column('clausula_referencia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis_documentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riesgos_contractuales_analisis_id'), 'riesgos_contractuales', ['analisis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riesgos_contractuales_analisis_id'), table_name='riesgos_contractuales')
    op.drop_table('riesgos_contractuales')
    op.drop_index(op.f('ix_fuentes_legales_consulta_id'), table_name='fuentes_legales')
    op.drop_table('fuentes_legales')
    op.drop_index(op.f('ix_comparaciones_documentos_usuario_id'), table_name='comparaciones_documentos')
    op.drop_table('comparaciones_documentos')
    op.drop_index(op.f('ix_analisis_documentos_documento_id'), table_name='analisis_documentos')
    op.drop_table('analisis_documentos')
    op.drop_index(op.f('ix_documentos_generados_usuario_id'), table_name='documentos_generados')
    op.drop_table('documentos_generados')
    op.drop_index(op.f('ix_documentos_usuario_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_consultas_usuario_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_normas_articulo'), table_name='normas')
    op.drop_table('normas')
    # ### end Alembic commands ###
